server:
  context-path: /
  port: 601


spring:
  datasource:
    # com.alibaba.druid.pool.DruidDataSource  com.mysql.cj.jdbc.Driver
    type:
    driver-class-name:
    druid:
      name: ius
      url:
      username:
      password:
      initial-size: 1
      min-idle: 1
      max-active: 5
      max-wait: 10000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 1800000
      validation-query: "SELECT 'x'"
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      pool-prepared-statements: false
      max-pool-prepared-statement-per-connection-size: -1

  redis:
    ## Redis数据库索引（默认为0）
    database: 1
    ## Redis服务器地址
    host: localhost
    ## Redis服务器连接端口
    port: 6379
    ## Redis服务器连接密码（默认为空,为空就不要写）
    password: null
    ## 连接超时时间（毫秒）
    timeout: 1200
    pool:
      ## 连接池最大连接数（使用负值表示没有限制）
      #spring.redis.pool.max-active=8
      max-active: 200
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
      #spring.redis.pool.max-wait=-1
      max-wait: 3
      ## 连接池中的最大空闲连接
      #spring.redis.pool.max-idle=8
      max-idle: 50
      ## 连接池中的最小空闲连接
      #spring.redis.pool.min-idle=0
      min-idle: 0



logging:
# only effective if logback-spring.xml not exists
  file: target/logs/activity/pumpkin-activity-api.log
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
    file: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"
  level:
    root: WARN
    org.springframework: WARN
    org.springframework.core: WARN
    org.springframework.test: WARN
    org.springframework.test.context: WARN
    org.springframework.test.context.junit4: WARN
    org.springframework.boot: WARN
    org.springframework.boot.test: WARN
    org.springframework.boot.test.context: WARN
    org.apache.tomcat: INFO
    org.apache.catalina: INFO
    org.eclipse.jetty: INFO
    org.apache.ibatis: WARN
    springfox: WARN
    org.apache.http: WARN